{"name": "test_access_control[admin-200]", "status": "broken", "statusDetails": {"message": "NameError: name 'api' is not defined", "trace": "user = 'admin', status_code = 200\n\n    @pytest.mark.parametrize(\n        (\"user\", \"status_code\"),\n        [\n            (\"admin\", 200),\n            (\"guest\", 403),\n            (\"\", 401)\n        ]\n    )\n    def test_access_control(user, status_code):\n>       response = api.login(user)\nE       NameError: name 'api' is not defined\n\ntests\\test_api.py:12: NameError"}, "parameters": [{"name": "user", "value": "'admin'"}, {"name": "status_code", "value": "200"}], "start": 1748006178942, "stop": 1748006178942, "uuid": "5a4d3871-4259-4164-a908-407b33899374", "historyId": "c5f9f814a2a422d358cbe6864f2cd3a6", "testCaseId": "156d2972e5a87051ba43e2b010fc8290", "fullName": "tests.test_api#test_access_control", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_api"}, {"name": "host", "value": "LAPTOP-S7QL1I5I"}, {"name": "thread", "value": "18660-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_api"}]}